confluentinc/confluent-kafka-go

README.md
- Moves the getting started section up so people will see it
- Adds specific instructions for install the go client
=> readme: move the getting started up so will people see it

kafka/producer.go
=> producer: Make events channel size configurable

kafka/testhelpers.go, kafka/testhelpers_test.go
=> move test helpers that need testing pkg to _test.go file

kafka/config.go, kafka/consumer.go, kafka/producer.go
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/162
=> Clone config before mutating it in NewProducer and NewConsumer

README.md, examples/confluent_cloud_example/confluent_cloud_example.go, examples/consumer_channel_example/consumer_channel_example.go, examples/consumer_example/consumer_example.go, examples/go-kafkacat/go-kafkacat.go, kafka/00version.go, kafka/README.md, kafka/api.html, kafka/config.go, kafka/consumer.go, kafka/consumer_performance_test.go, kafka/error.go, kafka/event.go, kafka/integration_test.go, kafka/kafka.go, kafka/producer_performance_test.go, kafka/producer_test.go, kafka/stats_event_test.go, kafkatest/go_verifiable_consumer/go_verifiable_consumer.go, kafkatest/go_verifiable_producer/go_verifiable_producer.go, mk/Makefile
Based on https://github.com/edenhill/librdkafka/issues/2020
=> v1.0 deprecations

kafka/kafka.go
=> doc: Fix typo

kafka/producer.go, kafka/producer_test.go
Add purge api to confluent kafka go, which is added to librdkafka in version 1.0.0
=> Add purge API

README.md, kafka/00version.go, kafka/config.go
Tagging @mhowlett and @rnpridgeon for review to show what needs to be done in confluent-kafka-dotnet and confluent-kafka-python
=> KIP-511: Client software name and version

kafka/consumer.go, kafka/offset.go, kafka/producer.go
assuming the html docs will get auto-generated in due course
=> Refine offsetsForTimes doc string

CHANGELOG.md, README.md, examples/cooperative_consumer_example/.gitignore, examples/cooperative_consumer_example/cooperative_consumer_example.go, kafka/00version.go, kafka/consumer.go, kafka/consumer_test.go, kafka/event.go, kafka/handle.go, kafka/integration_test.go, kafka/txn_integration_test.go
This can't be merged until there's a v1.6.0 librdkafka release (to be bundled), but I think it is good to have the review out of the way as soon as possible.
=> Incremental rebalancing

README.md
=> Medicate my OCD

examples/.gitignore, examples/README.md, examples/admin_create_acls/admin_create_acls.go, examples/admin_create_topic/admin_create_topic.go, examples/admin_delete_acls/admin_delete_acls.go, examples/admin_delete_topics/admin_delete_topics.go, examples/admin_describe_acls/admin_describe_acls.go, examples/admin_describe_config/admin_describe_config.go, examples/consumer_channel_example/consumer_channel_example.go, examples/consumer_example/consumer_example.go, examples/consumer_offset_metadata/consumer_offset_metadata.go, examples/cooperative_consumer_example/cooperative_consumer_example.go, examples/idempotent_producer_example/idempotent_producer_example.go, examples/oauthbearer_example/oauthbearer_example.go, examples/producer_channel_example/producer_channel_example.go, examples/producer_example/producer_example.go, examples/stats_example/stats_example.go, examples/transactions_example/generator.go, examples/transactions_example/processor.go, examples/transactions_example/transactions_example.go, examples/transactions_example/txnhelpers.go, examples/transactions_example/visualizer.go, kafka/adminapi.go, kafka/adminapi_test.go, kafka/adminoptions.go, kafka/api.html, kafka/error.go, kafka/integration_test.go
implements bindings for ACL operations:
CreateAcls
DescribeAcls
DeleteAcls
=> KIP-140: ACL operations

examples/confluent_cloud_example/confluent_cloud_example.go
* added SR serde with Confluent Cloud and authentication
=> changed confluent cloud example

schemaregistry/schemaregistry_client.go
When the key is not in cache and multiple goroutines
call the Serialize method at once, many of them could
start calls to SR to put in cache the same schema, this way
only the first one makes the call and the rest
read the cached result.
=> avoid cache stampede if key is not found.

CHANGELOG.md, kafka/00version.go, kafka/README.md, kafka/api.html, mk/doc-gen.py
=> release v1.9.1 preparation

kafka/api.html, kafka/build_darwin_amd64.go, kafka/build_darwin_arm64.go, kafka/build_glibc_linux.go, kafka/build_musl_linux.go, kafka/build_windows.go, kafka/generated_errors.go, kafka/librdkafka_vendor/rdkafka.h, schemaregistry/api.html
=> Import v1.9.2

CHANGELOG.md, examples/go.mod, kafka/api.html, mk/doc-gen.py, schemaregistry/api.html
- updated documentation after changing module version.
- documentation copyright link fix
=> Release 1.9.2 preparation

examples/admin_describe_config/admin_describe_config.go, kafka/adminapi.go
Fixes #750 
Tested on a local broker
=> [admin] Add IsDefault to ConfigEntryResult for DescribeConfigs

.github/workflows/base.yml, .semaphore/semaphore.yml, CHANGELOG.md, README.md, examples/go.mod, examples/stats_example/stats_example.go, kafka/00version.go, kafka/api.html, kafka/build_darwin_amd64.go, kafka/build_darwin_arm64.go, kafka/build_glibc_linux_amd64.go, kafka/build_glibc_linux_arm64.go, kafka/build_musl_linux_amd64.go, kafka/build_musl_linux_arm64.go, kafka/build_windows.go, kafka/config.go, kafka/generated_errors.go, kafka/librdkafka_vendor/rdkafka.h, mk/bootstrap-librdkafka.sh, mk/doc-gen.py, schemaregistry/api.html
Update librdkafka static bundle and Go client version to v2.0.0
=> Librdkafka static bundle v2.0.0

kafka/adminapi.go, kafka/adminapi_test.go, kafka/api.html, kafka/integration_test.go
rename DeleteConsumerGroupResult to DeleteConsumerGroupsResult
=> Rename GroupResult to ConsumerGroupResult,

examples/producer_example/producer_example.go
=> fix log message

schemaregistry/mock_schemaregistry_client.go, schemaregistry/schemaregistry_client.go
=> DGS-8011: Fix linter errors

schemaregistry/serde/protobuf/protobuf.go
Addresses https://github.com/confluentinc/confluent-kafka-go/issues/1052
=> return error for invalid message index count (and avoid makeslice crash)

examples/confluent_cloud_example/confluent_cloud_example.go, schemaregistry/config.go, schemaregistry/config_test.go, schemaregistry/rest_service.go, schemaregistry/rest_service_test.go, schemaregistry/schemaregistry_client.go
Flink Cell Operator wants to use bearer access token to connect to SR and it already has logic to get the token.
=> [DSG-8949] support Schema Registry bearer auth with static token

examples/avro_generic_consumer_example/avro_generic_consumer_example.go
=> Add error handling to avro_generic_consumer_example.go

examples/avro_specific_consumer_example/avro_specific_consumer_example.go
=> Add error handling to avro_specific_consumer_example.go

examples/avrov2_consumer_encryption_example/avrov2_consumer_encryption_example.go
=> Add error handling to avrov2_consumer_encryption_example.go

examples/avrov2_consumer_example/avrov2_consumer_example.go
=> Add error handling to avrov2_consumer_example.go

examples/avrov2_consumer_migration_example/avrov2_consumer_migration_example.go
=> Add error handling to avrov2_consumer_migration_example.go

examples/json_consumer_encryption_example/json_consumer_encryption_example.go
=> Add error handling to json_consumer_encryption_example.go

examples/json_consumer_example/json_consumer_example.go
=> Add error handling to json_consumer_example.go

examples/protobuf_consumer_encryption_example/protobuf_consumer_encryption_example.go
=> Add error handling to protobuf_consumer_encryption_example.go

examples/protobuf_consumer_example/protobuf_consumer_example.go
=> Add error handling to protobuf_consumer_example.go

README.md
Add error handling for SubscribeTopics call in High-level balanced consumer example
=> Add error handling for SubscribeTopics call in README.md

examples/confluent_cloud_example/confluent_cloud_example.go
=> Add error handling to confluent_cloud_example.go

examples/go-kafkacat/go-kafkacat.go
=> Add error handling to go-kafkacat.go

examples/legacy/consumer_channel_example/consumer_channel_example.go
=> Add error handling to consumer_channel_example.go

examples/oauthbearer_oidc_example/oauthbearer_oidc_example.go
=> Add error handling to oauthbearer_oidc_example.go

examples/stats_example/stats_example.go
=> Add error handling to stats_example.go

examples/mockcluster_example/mockcluster.go
Fixed inaccurate error logs for SubscribeTopics
=> Improve error logs in mockcluster.go

examples/consumer_rebalance_example/consumer_rebalance_example.go
=> Add error handling to consumer_rebalance_example.go

examples/confluent_cloud_example/confluent_cloud_example.go
consumer.Close() was unreachable
=> Fix unreachable code confluent_cloud_example.go

kafka/testresources/docker-compose.yaml
as 7.7.0 has bug https://issues.apache.org/jira/browse/KAFKA-16310 that makes LisOffsets test fail
=> Pinned cp-kafka version

schemaregistry/serde/avrov2/avro_test.go
* Add CSFLE tests with pre-canned data
* Minor cleanup
* Fix tests
=> Add CSFLE tests with pre-canned data  (#16)

schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/protobuf/protobuf_test.go
* Add JSON Schema ref test
* Minor cleanup
=> Add JSON Schema test with schema references (#17)

schemaregistry/serde/avrov2/avro.go, schemaregistry/serde/jsonschema/json_schema.go, schemaregistry/serde/protobuf/protobuf.go, schemaregistry/serde/rule_registry.go, schemaregistry/serde/serde.go
* Minor refactor to use RuleRegistry
* Minor cleanup
* Minor cleanup
=> Minor refactor to use RuleRegistry (#22)

CHANGELOG.md
* Update changelog for 2.5.4
* Minor fix
=> Update changelog for 2.5.4

schemaregistry/serde/avrov2/avro.go, schemaregistry/serde/avrov2/avro_test.go
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/1308
=> Fix handling of Avro schema evolution (#35)

schemaregistry/rules/cel/cel_executor.go, schemaregistry/serde/avro/avro_generic.go, schemaregistry/serde/avrov2/avro_util.go, schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/jsonschema/json_schema_util.go, schemaregistry/serde/protobuf/protobuf.go
Fix handling of nested maps for Avro and JSON Schema
=> Fix handling of nested maps for Avro and JSON Schema

schemaregistry/rules/cel/cel_executor.go, schemaregistry/rules/cel/cel_field_executor.go, schemaregistry/rules/encryption/encrypt_executor.go, schemaregistry/rules/jsonata/jsonata_executor.go, schemaregistry/serde/avrov2/avro_test.go, schemaregistry/serde/rule_registry.go, schemaregistry/serde/serde.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Add ability to override disable flag and actions on a rule

schemaregistry/rules/encryption/awskms/aws_driver.go
What
----
Minor enhancement to allow AWS roles to be specified. This was tested manually with actual AWS IAM roles.
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Add AWS AssumeRole support to AWS KMS

schemaregistry/config.go
What
----
Change max retry default from 2 to 3 based on internal review.
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Minor change to default for client retries

service.yml, sonar-project.properties
What
----
Checklist
- **No code changes**
References
----------
JIRA: 
Test & Review
------------
=> Exclude examples/ from code coverage report

examples/avrov2_consumer_encryption_example/avrov2_consumer_encryption_example.go, examples/json_consumer_encryption_example/json_consumer_encryption_example.go, examples/protobuf_consumer_encryption_example/protobuf_consumer_encryption_example.go
What
----
Add comments regarding rule config to CSFLE consumer examples
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Add comments regarding rule config to CSFLE consumer examples

CHANGELOG.md
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Update changelog for SR for 2.8.0

schemaregistry/config.go, schemaregistry/internal/client_config.go, schemaregistry/rules/encryption/encrypt_executor.go, schemaregistry/rules/encryption/encrypt_executor_test.go
What
----
Enhance error handling for CSFLE configure method
Checklist
References
----------
JIRA: 
Test & Review
------------
=> DGS-19519 Enhance error handling for CSFLE configure method

schemaregistry/serde/protobuf/protobuf.go
What
----
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/1382
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Fix panic if deserialization fails in DeserializeInto

schemaregistry/serde/jsonschema/json_schema.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Minor refactoring - move JSON validation after rules

.semaphore/project.yml, .semaphore/semaphore.yml
This reverts commit e0d266ffa012a2ae8c7dcce5c81c14fd91c9f88a.
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Revert "chore: update repo by service bot (#1361)"

schemaregistry/serde/avrov2/avro_test.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Add test for nested Avro map

schemaregistry/internal/rest_service.go
What
----
Refactor use of httpclient.  Call NewRequest method to construct a Request, which will set the Content-Length appropriately.
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Refactor use of httpclient

schemaregistry/rules/encryption/deks/dekregistry_client.go, schemaregistry/rules/encryption/deks/mock_dekregistry_client.go, schemaregistry/rules/encryption/encrypt_executor.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> DGS-19840 Ensure use of DEK object is thread-safe

schemaregistry/rules/encryption/encrypt_executor.go, schemaregistry/serde/serde.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> MINOR refactor of DEK creation

schemaregistry/confluent/types/decimal.proto, schemaregistry/serde/protobuf/decimal_util.go, schemaregistry/serde/protobuf/decimal_util_test.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> DGS-20014 Add utilities to convert decimals from/to Protobuf

examples/schema_registry_bearer_authentication/bearer_authentication.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Sr oauth examples

examples/schema_registry_bearer_authentication/bearer_authentication.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Fix examples file

examples/schema_registry_bearer_authentication/bearer_authentication.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Fix linting issues

.semaphore/semaphore.yml
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Fix Semaphore CI after Ubuntu 24 upgrade

schemaregistry/rules/encryption/encrypt_executor.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Fix possible NPE in CSFLE executor

schemaregistry/internal/rest_service.go, schemaregistry/mock_schemaregistry_client.go, schemaregistry/rules/encryption/deks/dekregistry_client.go, schemaregistry/rules/encryption/deks/mock_dekregistry_client.go, schemaregistry/rules/encryption/encrypt_executor.go, schemaregistry/schemaregistry_client.go, schemaregistry/serde/avro/avro_generic.go, schemaregistry/serde/avro/avro_specific.go, schemaregistry/serde/avrov2/avro.go, schemaregistry/serde/avrov2/avro_test.go, schemaregistry/serde/jsonschema/json_schema.go, schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/protobuf/protobuf.go, schemaregistry/serde/protobuf/protobuf_test.go, schemaregistry/serde/serde.go, schemaregistry/serde/serde_test.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Support for schema id in header

.semaphore/semaphore.yml
What
----
This changes the macOS Semaphore job to use ARM instead of AMD. This is 40% cheaper.
Checklist
References
----------
JIRA: 
Test & Review
------------
PR checks
=> change to ARM macOS Semaphore agent

schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/jsonschema/json_schema_util.go
What
----
Fix transformation of union of JSON refs
Checklist
- [Y] Contains customer facing changes? Including API/behavior changes 
- [Y] Did you add sufficient unit test and/or integration test coverage for this PR?
References
----------
JIRA: 
Test & Review
------------
=> DGS-22343 Fix transformation of union of JSON refs
