kafka/config.go, kafka/message.go
Golang 1.2 seems to be the default version on Ubuntu 14.04.
This PR fixes compilation errors for Go 1.2
=> Fix compilation errors on Go 1.2

kafka/config.go
fmt.Stringer is an existing interface that defines the `String() string` method.
In addition, the case statement now includes the type asserted value that can be
use directly in the case blocks.
Signed-off-by: Byron Ruth b@devel.io
=> Replace stringable with fmt.Stringer

kafka/README.md
Just general tidying, it's good to stick with markdown throughout.
=> Fixup markdown and rename to readme.md

kafka/consumer.go, kafka/consumer_test.go
Using rd_kafka_seek implemented in the rdkafka library we just expose this on the consumer interface. I had this take a `TopicPartition` as the argument to match the way other methods worked but I can switch it to take topic/partition/offset args if that makes more sense.
=> Add Seek API to consumer

kafka/consumer.go, kafka/event.go, kafka/event_test.go, kafka/producer.go, kafka/stats_event_test.go
@edenhill Please review the changes along with the librdkafka PR https://github.com/edenhill/librdkafka/pull/1171 ("added support for stats as events")
=> Expose the librdkafka stats as events in the go client

examples/consumer_channel_example/consumer_channel_example.go
the example works as is (though maybe only 99.99% of the time?), but this tripped me up when I extended the select statement to do more things. refer to: https://golang.org/pkg/os/signal/#Notify
=> buffer signal channel

kafka/consumer.go, kafka/consumer_test.go
Expose librdkafka's `rd_kafka_offsets_store()` introduced in v0.11.0 (not yet released).
Consumer.OffsetsStore() allows manual control over the committed offsets without sacrificing auto-commit functionality.
I am not sure if returning the storedOffsets is the correct thing to do, we could stop returning them to keep the API cleaner, or return a list of the failed TopicPartitions.
=> Added Consumer.OffsetsStore()

README.md
'go get' will fail on mac if you don't have pkg-config installed.
=> explicit call out that you may need pkg-config

kafka/consumer.go
This PR let `Consumer` to close `consumer.events` channel when calling `Consumer.Close()`. In this way, we can use the following code to consume data from `Consumer`, and exit automatically when `Consumer.Close()` is called.
```go
for ev := range consumer.Events() {
// do something here
}
```
=> Close event channel when consumer is closed

README.md
In Golang `for {` would loop forever and is effectively the same as `for true {`.
=> Simplify for loop

.travis.yml, README.md, kafka/00version.go, kafka/build_dynamic.go, kafka/build_static.go, kafka/build_static_all.go, kafka/consumer_test.go, kafka/integration_test.go
Two reasons:
* `pkg-config --static ..` doesn't really work well.
* Go 1.10 added constraints to what compiler.et.al flags that may be passed, `pkg-config --static` was not one of them.
=> Use librdkafka's new -static pkg-config

README.md
Fixed bug memory leak (important bug !)
by closing Producer
=> defer p.Close() in producer, avoid memory leak

mk/doc-gen.py
Some browsers may not pull unencrypted resources that are referenced from encrypted pages. Which causes the styling to be broken on https://docs.confluent.io/current/clients/confluent-kafka-go/index.html in Chrome.
https://www.dropbox.com/s/zzcj5axukisyvk6/Screenshot%202018-04-30%2011.01.03.png?dl=0
=> Use same scheme as the HTML document in docs

kafka/metadata.go
When GetMetadata is called, a C struct is created for holding this data,
but then is never released again after data is copied to a Go struct. This adds a release for that memory
I believe this addresses #210.
=> Fix metadata memory leak

kafka/adminapi.go, kafka/error.go
Makes possible to create `kafka.Error` objects which is useful for unit testing. 
Closes https://github.com/confluentinc/confluent-kafka-go/issues/302
=> Rename newGoError to NewError

kafka/consumer.go, kafka/integration_test.go, kafka/metadata.go
This PR exposes the [`rd_kafka_get_watermark_offsets`](https://github.com/edenhill/librdkafka/blob/8ea4c10549d5fab2d417e46f9a6e89c852c6e7b7/src/rdkafka.h#L2456) API as `GetWatermarkOffsets`
This is similar to `QueryWatermarkOffsets` except that it does not query the broker for the offsets, it will return the values that are internally cached on the client.  For the purposes of calculating the consumer lag, this is sufficient because the "high watermark" is returned with every fetch request so it will be available while consuming.  
Having this API allows consumers to calculate the lag while avoiding the overhead of either querying the broker or generating and parsing the statistics JSON
=> Add GetWatermarkOffsets API

examples/confluent_cloud_example/confluent_cloud_example.go
This PR essentially improves the developer experience of users trying this example with Confluent Cloud. Here is the link of changes made:
- The import has been changed from 'github.com/confluentinc/confluent-kafka-go/kafka' to 'gopkg.in/confluentinc/confluent-kafka-go.v1/kafka' to be in line with what the docs suggest.
- Instructions regarding how the user can retrieve information about the bootstrap server and API key has been provided, according to the behavior of the new CCloud CLI.
- The information about the bootstrap server and the API key have been made available in the code as constants, and now they are reused across the Admin API, the producer, and the consumer.
- A new function called 'createTopic()' was created to automatically create the topic for the user. This reduces the …
=> Improve the Confluent Cloud Go example for better Developer Experience

examples/.gitignore, examples/README, examples/consumer_offset_metadata/consumer_offset_metadata.go, kafka/kafka.go
Added ability to commit offset with metadata that represents the state of the partition consumer at that point in time. The metadata string can be used by another consumer to restore that state, so it can resume consumption.
=> Offset metadata

examples/confluent_cloud_example/confluent_cloud_example.go
these config settings are not needed post v1.0.
=> Simplify Confluent Cloud example config

kafka/adminapi.go, kafka/adminapi_test.go, kafka/context.go, kafka/integration_test.go, kafka/time.go
Issue: https://github.com/confluentinc/confluent-kafka-go/issues/319
=> #319: Add ClusterID and ControllerID to AdminClient.

kafka/config.go, kafka/consumer.go
Learning how to use Go Kafka and noticed spelling mistakes in the comments of `kafka/consumer.go` and `kafka/config.go`
=> Fix spelling in a couple comments

kafka/config.go
The librdkafka rd_kafka_conf_set and rd_kafka_topic_conf_set functions do not take ownership of the C strings passed as key-value. We need to always free them, not only on error.
Issue: https://github.com/confluentinc/confluent-kafka-go/issues/402
=> Free key-value C strings used in anyconfSet.

kafka/config.go, kafka/consumer.go, kafka/consumer_test.go, kafka/handle.go, kafka/log.go, kafka/producer.go
.. and some refactoring.
.. and include the client instance name in the LogEvent.
.. and cache the client instance name to avoid CGo call for each stringification.
=> Added "go.logs.channel" property for passing an existing channel to log to

kafka/kafka.go, kafka/librdkafka/librdkafka.go
Prior to this the librdkafka/ sub-directory (which contains headers and prebuilt librdkafka libs) would be pruned by `go mod vendor`.
Not sure how this will work with gopkg.in (since the package path wont match), but people should be using go modules.
=> Add dummy Go file to librdkafka sub dir so it is not pruned during vendor import (#450)

kafka/consumer.go, kafka/kafka.go
- Fix typo
- change `experimental` to `deprecated` and move it earlier in the line so it's not lost in the scroll
=> docs tweaks

kafka/01nocgo.go, kafka/integration_test.go
This is how it will look to the user:
```bash
$ GOOS=linux go build
../confluent-kafka-go/kafka/01nocgo.go:15:2: cannot find package "ConfluentKafkaGo_CANT_BE_CROSS_COMPILED" in any of:
/usr/local/bin/go/src/ConfluentKafkaGo_CANT_BE_CROSS_COMPILED (from $GOROOT)
../confluent-kafka-go/kafka/01nocgo.go:16:2: cannot find package "ConfluentKafkaGo_REQUIRES_CGO_ENABLED" in any of:
/usr/local/bin/go/src/ConfluentKafkaGo_REQUIRES_CGO_ENABLED (from $GOROOT)
```
Which, despite the hack of using dummy imports, provides a far more useful
error message than the current:
```bash
$ GOOS=linux go build
.....: undefined: "gopkg.in/confluentinc/confluent-kafka-go.v1/kafka".Event
.....: undefined: "gopkg.in/confluentinc/confluent-kafka-go.v1/kafka".Message
....
...lots of lines..
```
=> Improve user experience when attempting unsupported cross-compilation

README.md
[as with python] i think it makes sense to put this text after the license.
i think it's a bit too heavy though and low impact to be putting near the top, so i moved the license, and this down the bottom.
although i like the license up the top (it's something to advertise), i don't see any issue in not doing this - people are used to seeking out license, and we don't make it hard to find (there's a LICENSE.txt file).
=> Added ASF notice to README

kafka/handle.go, kafka/message.go, kafka/producer.go, kafka/producer_test.go
@edenhill 
This configuration property will allow users to enable/disable certain fields of the delivery reports to reduce allocations.
Only the key & value are currently supported
Addresses #524
=> Add support for go.delivery.report.fields

.travis.yml
It seems the travis tests are failing because they're timing out. Bumping the timeout to see if that fixes it, or if the timeout is actually the result of some other brokenness.
EDIT: yeah that seems to be all it took. @mhowlett What do you think, should we merge this?
=> Bump timeout on go test command

CHANGELOG.md, kafka/adminapi.go, kafka/adminapi_test.go
This is the fix for https://github.com/confluentinc/confluent-kafka-go/issues/616
librdkafka supports AdminClient.CreateTopics(...) with default value(-1) of NumPartitions and ReplicationFactor, but currently it's not possible to pass a value of -1 or 0 for ReplicationFactor to CreateTopics without specifying an explicit ReplicaAssignment.
=> Default parameters for AdminClient#createTopic

CHANGELOG.md, kafka/event.go, kafka/glue_rdkafka.h, kafka/handle.go, kafka/message.go, kafka/producer.go, kafka/producer_test.go
Disabled by default due to the extra CGo calls required (costly) and the deserialization of C headers to Go Headers.
=> Add headers to go.delivery.report.fields (disabled by default)

README.md
Using the examples verbatim from the README as a quick start, you run into this problem https://github.com/confluentinc/confluent-kafka-go/issues/510
Using github imports solves the issue, especially for new users quickly
=> Update imports in README to use github imports instead

.travis.yml, soaktest/README.md, soaktest/datadog.go, soaktest/soakclient/soakclient.go, soaktest/soakclient_transaction/soakclient_transaction.go, soaktest/soaktest.go
Running with 2 processes for soak test: 
Process-1 : Create Producer-1 to keep sending messages to the input-topic.
Create Consumer-2 to receive messages from the output-topic.
Process-2: Create Consumer-1 to receive messages from the input-topic.
Create transactional producer Producer-2 to sending the received messages to the output-topic.
The initTransaction API registers a transactional.id when creating the producer.
The producer sends the messages to the output-topic.
Commit transaction after sending 100 messages each time or 1 second.
There are 3 new files added:
1. soakclient_test.go: implementation of Process-1, Creating topics, and common functions used by both processes include: Producer delivery checking, Stats Events handling and received message handling
2. …
=> Soak test for go client

examples/consumer_example/consumer_example.go
static check complaining that `== true` is superfluous for a boolean var.
=> Silence golang static checker

kafka/event.go
it seems the author forget these according to the context.
ref: 8f7dd3a59617ca4746d99bfd24ff487f2dfc13db
@edenhill
=> correct handle's eventPoll RD_KAFKA_EVENT_DR term

examples/mockcluster_example/mockcluster.go, examples/mockserver_example/mockserver.go, kafka/adminapi.go, kafka/adminoptions.go, kafka/config_test.go, kafka/consumer_performance_test.go, kafka/consumer_test.go, kafka/context.go, kafka/error_test.go, kafka/event_test.go, kafka/header_test.go, kafka/integration_test.go, kafka/kafka.go, kafka/kafka_test.go, kafka/librdkafka_vendor/rdkafka_mock.h, kafka/message_test.go, kafka/metadata_test.go, kafka/misc.go, kafka/mockcluster.go, kafka/offset.go, kafka/producer.go, kafka/producer_performance_test.go, kafka/producer_test.go, kafka/select_rdkafka.h, kafka/testhelpers_test.go, kafka/time.go, kafka/txn_integration_test.go
Hi,
this PR exposes the MockCluster from librdkafka to Golang. 
You are able to start a MockCluster with:
`kafka.NewMockCluster(1)`
and read the corresponding bootstrap.servers property via:
`broker := mockCluster.Bootstrapservers()`
Remote communication is also possible.
An example is also added.
Thanks,
Kristian
=> Create a MockCluster within Go for testing

service.yml
For semaphore CI migration, we need to first add new project to semaphore  CI.
=> Add service.yml for adding new project to semaphore CI

CHANGELOG.md, kafka/consumer.go, kafka/consumer_test.go
Author @jliunyu.
Update the consumer close function with the latest rd_kafka_consumer_close_queue API
=> Update the consumer close function with the latest rd_kafka_consumer_close_queue API

kafka/adminapi.go, kafka/api.html
Removed non-existent wildcard pattern type in documentation and explained it better.
=> fix: removed wildcard pattern type in documentation

schemaregistry/serde/avro/avro_generic_test.go, schemaregistry/serde/avro/avro_specific.go, schemaregistry/serde/avro/avro_specific_test.go
1. Fixes avro_specific Deserialize method which did not return the
right thing (it did not return anything useable).
2. Update tests for (1) - add Deserialize to tests which were only
testing DeserializeInto
3. Add Deserialize to avro_generic tests as well.
Addresses  #843
=> Fix Deserialize (avro_specific) and improve tests for avro_specific/avro_generic

README.md
We can either make sure to ensure that the gcc version mismatch isn't there, or use musl for static builds.
=> [docs] Add instructions on building a static executable for Linux

kafka/librdkafka_vendor/README.md
It's worth noting in the README there's a new statically built Apple silicon image.
=> Add info about arm64 statically built target

CHANGELOG.md, README.md, kafka/consumer.go, kafka/consumer_test.go, kafka/error.go
This convenience method just checks if Error code is ErrTimedOut.
Also modifies the example in README.md.
See https://github.com/confluentinc/confluent-kafka-go/pull/846#discussion_r1030215346
=> Add IsTimeout method to Error

kafka/error_gen.go, kafka/generated_errors.go, kafka/integration_test.go
An integration test which should be checking for testconf.json, was not checking for it correctly, and wasn't being skipped due to that.
There were several issues with formatting, all of them in the generated error file. All those have been fixed along with the generation code.
Additionally, there are a few errors in the _build files, but they won't be fixed till we bump our go version to 1.17 (+build is replaced with go:build, and gofmt 1.18+ expects go:build, but we are going to stick to go 1.14 for now).
All this is needed for setting up a Github Actions workflow effectively.
=> Fix gofmt errors and broker check on integration test

kafka/producer.go, kafka/producer_test.go
A recent refactor of the underlying init_transactions code in terms of timeouts and the ability to retry requires changes in TestTransactionalAPI test.
=> [producer] Fix TestTransactionalAPI for InitTransactions changes

CHANGELOG.md, kafka/consumer.go, kafka/consumer_test.go
Seek timeout is ignored and an infinite timeout is used instead. The method will block till fetcher state is updated and the seek is registered.
See #888.
=> [consumer] Ignore Seek() timeout

.github/workflows/base.yml, mk/Makefile
1. build
2. test
3. gofmt
4. make-docs
Changes Makefile to have option to specify go tags for dynamic linking. We need to link dynamically against librdkafka whenever we run an action, because there might be changes in master which we haven't brought over to this repository yet.
Currently the last step (test) for the first job fails, because some recent changes in librdkafka cause the failure of TestTransactionalAPI. So, this PR should ideally be merged only after those have been fixed, else the built-test-doc job will always fail.
=> Add Github Actions setup

CHANGELOG.md, README.md, kafka/README.md
The go version is updated because 1.11 has been long out of support, and parts of the code are already using features only available in 1.13+. 
The oldest version of go officially supported (by the golang team) is 1.18, but that is a bit too aggressive for us, and so we go for 1.14. 
And as for preferring go1.18 for development, it's because go1.19 has a bunch of changes in gofmt etc, and the release has been out only recently. So we will stick to 1.18 till it's out of support, and then make the changes to all files with the new gofmt.
=> Update go version and add developer instructions

.semaphore/semaphore.yml, kafka/README.md, kafka/adminapi.go, kafka/build_dynamic.go, kafka/config.go, kafka/config_test.go, kafka/consumer.go, kafka/consumer_test.go, kafka/error_test.go, kafka/integration_test.go, kafka/kafka.go, kafka/kafka_test.go, kafka/message.go, kafka/message_test.go, kafka/producer.go, schemaregistry/cache/lrucache.go, schemaregistry/cache/mapcache.go, schemaregistry/test/nested.pb.go
Go 1.18 is no longer supported officially from today. (See https://go.dev/dl/)
Go 1.19 needs to be set as the development version.
1. Change the kafka/README.md
2. Run gofmt on all the code, since go1.19 makes several changes in gofmt, and doing it at once prevents it from happening in a piecemeal fashion later on.
=> Change development version to go1.19

CHANGELOG.md, kafka/consumer.go, kafka/consumer_test.go, kafka/integration_test.go
Allows seeking multiple partitions.
Deprecates Seek(), which supports seeking single partition.
See https://github.com/confluentinc/confluent-kafka-go/issues/902
Added for replacing #907 since it's on a fork.
=>  [consumer] Add SeekPartitions to Consumer  

schemaregistry/rest_service.go
#943 - Should fix this(Supports all schema-registry base urls which have existing path).
=> Fix Url Parsing in Schema Registry

CHANGELOG.md, kafka/kafka_test.go, kafka/offset.go
Closes #778 
Adding the ability to use a concrete Offset type with the NewOffset func, by extension this also enables it through the Offset.Set func.
An Offset is an int64 type in itself, so it can be returned as such.
=> add offset type to NewOffset func

CHANGELOG.md, README.md
Since the issue in 2.1.0 is quite severe, it's probably good to include it in the CHANGELOG.md
=> Update README and CHANGELOG for 2.1.1

CHANGELOG.md, kafka/consumer.go, kafka/integration_test.go, kafka/kafka.go, kafka/message.go
msg.TopicPartition.LeaderEpoch is used when storing offsets, that field now is also used when returning the leader epoch associated to the message, similar to what happens with the offset.
=> Deprecate msg.LeaderEpoch

schemaregistry/mock_schemaregistry_client.go, schemaregistry/schemaregistry_client.go
This is a port of the corresponding functionality in the Java client at https://github.com/confluentinc/schema-registry/pull/2658
=> DGS-8011 Add cache for GetSchemaMetadata

kafka/consumer.go, kafka/integration_mock_test.go
See #1062
https://github.com/confluentinc/confluent-kafka-go/pull/901#issuecomment-1688151851
With #901, such flows were no longer working after the final Close(). 
```
rebalanceCb() {
...
...
if (partitions_are_being_revoked) { 
commit(some_offsets) 
}
```
This was because the consumer would be counted as closed and commit would return an error.
it's based on the dev_go_flush_ignore_queue_buffering_time since I'm using the same file
=> Allow consumer methods to run while closing

schemaregistry/rest_service.go
This resolves issue [1064](https://github.com/confluentinc/confluent-kafka-go/issues/1064)
=> honor HTTPS_PROXY environment variable

examples/admin_list_offsets/admin_list_offsets.go, kafka/adminapi.go, kafka/adminapi_test.go, kafka/adminoptions.go, kafka/integration_test.go
DescribeTopics and ListOffsets should return an empty output if and empty input is passed as parameter.
Consistent with Java and user friendly for users using filter and map.
=> Fix calls with empty lists

schemaregistry/config.go, schemaregistry/rest_service.go
Allow custom http.Client to be passed to SR client
=> Allow custom http.Client to be passed to SR client

schemaregistry/schemaregistry_client.go
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/1055
=> Minor optimization to cache latest schema

schemaregistry/serde/avro/avro_generic.go, schemaregistry/serde/avro/avro_specific.go, schemaregistry/serde/jsonschema/json_schema.go, schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/protobuf/protobuf.go, schemaregistry/serde/serde.go
Ensure the schema info is updated before using it for JSON validation.
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/1078
Supercedes https://github.com/confluentinc/confluent-kafka-go/pull/984
=> Fix json validation during serialization

.semaphore/semaphore.yml
- Update mac agent to 13.5 which is close to developer's local versions.
- new mac agent syntax is same as ubuntu agents
=> ci: Update mac build agents versions

schemaregistry/cache/cache.go, schemaregistry/cache/lrucache.go, schemaregistry/cache/mapcache.go, schemaregistry/config.go, schemaregistry/schemaregistry_client.go
Add CacheLatestTtlSecs to allow expiration of latest schemas
=> Add CacheLatestTtlSecs to allow expiration of latest schemas

kafka/adminapi.go, kafka/adminoptions.go, kafka/error_gen.go, kafka/generated_errors.go, kafka/message.go
Use the `const Name Type = expression` syntax for all typed enum constants. This causes the godoc tool to group the consts with the type definition, which makes it easier to find in the package API documentation.
The godoc tool does not group consts if the type comes from the right hand side, as `const Name = Type(expression)`. This is the syntax the kafka package uses. This means most enum const values are not easily found. For example, type OffsetSpec does not show the defined constant values:
https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka#OffsetSpec
Instead, the constants are in the package Constants section at the top:
https://pkg.go.dev/github.com/confluentinc/confluent-kafka-go/v2@v2.3.0/kafka#pkg-constants
The ErrorCode type uses the correct syntax: …
=> godoc: Change const groups so enum values are grouped with type

kafka/producer.go
The way I understand it, the text about `transaction.timeout.ms` is relevant for `BeginTransaction` and not for `InitTransactions` (but please correct me if I'm misunderstanding this).
=> Move doc from InitTransactions to BeginTransaction

schemaregistry/serde/protobuf/protobuf.go
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/969
=> Cache parsed file descriptors

schemaregistry/serde/protobuf/protobuf.go, schemaregistry/serde/protobuf/protobuf_test.go
The protobuf deserialization code would panic when given an empty, non-nil payload. This fixes the panic by checking for this case before doing any processing.
Test: added a test to reproduce and ensure that this fixes the panic
=> fix empty payload panic in protobuf deserialization

schemaregistry/serde/protobuf/config.go, schemaregistry/serde/protobuf/protobuf.go, schemaregistry/serde/protobuf/protobuf_test.go, schemaregistry/serde/testhelpers.go
This adds code to the Serializer that caches the `SchemaInfo` for each `FileDescriptor`, which improves performance by over an order of magnitude by caching the string manipulation bottleneck (see flamegraph [here](https://github.com/confluentinc/confluent-kafka-go/issues/1146#issuecomment-1983975280)). In order to do this, there was also some refactoring to isolate the "cachable" code (getting SchemaInfo from a proto).
Benchmark results:
```
go test -bench . -benchmem
goos: darwin
goarch: arm64
pkg: github.com/confluentinc/confluent-kafka-go/v2/schemaregistry/serde/protobuf
BenchmarkProtobufSerWithReference-8         	   30640	     38625 ns/op	  21778 B/op	     696 allocs/op
BenchmarkProtobufSerWithReferenceCached-8   	 1000000	      1047 ns/op	   1089 B/op	      10 allocs/op …
```
=> add CacheSchemas option to Serializer

schemaregistry/mock_schemaregistry_client.go, schemaregistry/rest_service.go, schemaregistry/serde/avrov2/avro_test.go, schemaregistry/serde/jsonschema/json_schema.go, schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/protobuf/protobuf_test.go, schemaregistry/serde/serde.go
Inside the schemaregistry:
- Added error handling for unchecked errors.
- Replaced unused variables with blank identifiers.
- Removed unused code.
- Removed redundant type specifications.
- Fixed typos.
=> chore: cleanup schemaregistry and improve error handling

examples/avrov2_producer_encryption_example/avrov2_producer_encryption_example.go
schemaregistry.Rule type is inferred by `[]schemaregistry.Rule{`
=> Removed redundant type in avrov2_producer_encryption_example.go

examples/admin_describe_cluster/admin_describe_cluster.go
The results print was printing a pointer to clusterDesc.ClusterID and not the cluster id itself
=> Fix issue in admin_describe_cluster.go

schemaregistry/internal/rest_service.go, schemaregistry/rest/rest_error.go, schemaregistry/rules/encryption/deks/mock_dekregistry_client.go, schemaregistry/rules/encryption/encrypt_executor.go
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/1300
=> Move internal RestError to public rest.Error (#30)

CHANGELOG.md, examples/admin_list_consumer_groups/admin_list_consumer_groups.go, kafka/adminapi.go, kafka/adminapi_test.go, kafka/adminoptions.go, kafka/integration_test.go
an optional filter to return only groups of given types
=> [KIP-848 EA] Admin API for listing consumer groups now has 

schemaregistry/serde/avrov2/avro_test.go, schemaregistry/serde/avrov2/avro_util.go, schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/jsonschema/json_schema_util.go
Support transforming maps in Data Contract rules.  Previously only transforming fields in structs were supported.  This PR adds ability to transform entries in maps.
=> Support transforming maps in Data Contract rules

schemaregistry/config.go, schemaregistry/internal/client_config.go, schemaregistry/internal/rest_service.go, schemaregistry/internal/rest_service_test.go
Add retry logic to RestService.  We implement exponential backoff with full jitter per https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
=> Add retry logic to RestService

schemaregistry/serde/protobuf/protobuf.go, schemaregistry/serde/protobuf/protobuf_test.go
The copying is only needed for the DeserializeInto method for Protobuf.
=> For Protobuf, copy the result into the target if necessary

schemaregistry/rules/cel/cel_executor.go, schemaregistry/serde/jsonschema/json_schema_test.go
Don't register maps as native types in CEL rules.
Fixes an error where "unsupported reflect.Type map[string]interface{}, must be reflect.Struct" was being returned when a map was passed into the CEL rule
=> Don't register maps as native types in CEL rules

schemaregistry/rules/encryption/awskms/aws_client.go, schemaregistry/rules/encryption/azurekms/azure_client.go
Ensure different key ids use different client instances.
=> Ensure different key ids use different client instances

schemaregistry/internal/client_config.go, schemaregistry/internal/rest_service.go, schemaregistry/serde/avrov2/avro_test.go
What
----
Add support for comma-separated URLs for SR.
Fixes https://github.com/confluentinc/confluent-kafka-go/issues/1156
Checklist
- Yes
- Tested manually
References
----------
JIRA: 
Test & Review
------------
=> Add support for comma-separated URLs

schemaregistry/internal/rest_service.go, schemaregistry/rules/encryption/deks/dekregistry_client.go, schemaregistry/serde/avrov2/avro_test.go
What
----
Ensure algorithm query param is passed for CSFLE
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Ensure algorithm query param is passed for CSFLE

schemaregistry/internal/rest_service.go
What
----
Fix HTTP retries that send a body to actually send the body on retries.
Checklist
- No: no existing tests for retry payloads
References
----------
JIRA: https://github.com/confluentinc/confluent-kafka-go/issues/1393
Test & Review
------------
Local testing only
=> ISSUE-1393 send the body on each http.Request retry

kafka/integration_mock_test.go
by awaiting for an assignment before closing the consumer, so it's sure a revocation must happen.
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> Fix flaky test TestConsumerMethodCallsWhileClosing

CHANGELOG.md, kafka/adminapi.go, kafka/integration_test.go
This PR intends to add support for Group Resource type for IncrementalALterConfigs API as specified in KIP 848 and extended the DescribeConfigs support till API version 3.
Additional changed the integration test to check for Group Resource Type.
Librdkafka PR: https://github.com/confluentinc/librdkafka/pull/4939
=> KIP 848:Extend DescribeConfigs and IncrementalAlterConfigs to support GROUP Config

service.yml
What
----
This changes the `service.yml` so that cc-service-bot will no longer try to manage the contents of `.semaphore/semaphore.yml`.
Checklist
References
----------
JIRA: 
Test & Review
------------
N/A - can only be tested on the default branch
=> disable cc-service-bot's management of the Semaphore pipeline contents

examples/docker_aws_lambda_example/go.sum, schemaregistry/rules/encryption/encrypt_executor.go, schemaregistry/serde/avrov2/avro_test.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> DGS-21595 Allow alternate KMS key IDs on a KEK 

schemaregistry/serde/jsonschema/json_schema_test.go, schemaregistry/serde/jsonschema/json_schema_util.go
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
=> DGS-21988 Fix transformation of nullable JSON props
